// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAsyyEdMcNT0T5ZKipwVyLmkxAvVV6HQ',
    appId: '1:954534258387:web:89737bd2c9eb9a9fc75626',
    messagingSenderId: '954534258387',
    projectId: 'instagram-clone-ceac3',
    authDomain: 'instagram-clone-ceac3.firebaseapp.com',
    storageBucket: 'instagram-clone-ceac3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzXNIFNUMAsqEpOvHnsywAOvoXEcm8NHc',
    appId: '1:954534258387:android:05b0bb037355ccf3c75626',
    messagingSenderId: '954534258387',
    projectId: 'instagram-clone-ceac3',
    storageBucket: 'instagram-clone-ceac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQ2VGhfM80g4Eqyog6iLACMhi24R8BD8',
    appId: '1:954534258387:ios:60bc0f09b60389d0c75626',
    messagingSenderId: '954534258387',
    projectId: 'instagram-clone-ceac3',
    storageBucket: 'instagram-clone-ceac3.appspot.com',
    iosClientId: '954534258387-g445krddv66i7vr2nqk0fqct2bc36db0.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
